baseURL: /
languageCode: en-us
title: MustDeliver
theme: mustDeliverTheme
params:
  mainMenu:
    - name: Home
      url: /home
      active: true
    - name: Platform
      url: javascript:void(0)
      subitems:
        - name: Marketplace
          url: /marketplace
        - name: TMS
          url: /tms
        - name: Pricing Model
          url: /pricing
    - name: Shippers
      url: /shipper
    - name: Carriers
      url: /carrier
    - name: About
      url: /about
    - name: Support
      url: /support
      subitems:
        - name: Shipper FAQ’s
          url: /shipper-faqs
        - name: Carrier FAQ’s
          url: /carrier-faqs
        - name: Carrier Registration Guide
          url: /registration-guid
        - name: Carrier Tracking, Completing Loads
          url: /tracking

contactInfoTitle: "Contact Info"
contactNumber: 
        - number: "1 833 933 1833"

contactAddress: 
        - address: "6 State Street, Suite 308Bangor,\n\n Maine 04401"
contactEmail: 
        - email: "carrier@mustdeliver.com"
        - email: "shipper@mustdeliver.com"
